version: '3'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: santos0santos0/nginx:latest
    container_name: nginx
    networks:
      - nginx_network
    ports:
      - "8080:80"
    depends_on:
     - app

  app:
    build:
      context: .
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 120s node index.js
    networks:
      - nginx_network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
     - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db
    image: santos0santos0/db:latest
    command: 
      --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=challenge
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx_network
  
networks:
  nginx_network:
    driver: bridge
